export const CITY_FETCHING = 'CITY_FETCHING';
export const CITY_FETCHED = 'CITY_FETCHED';
export const CITY_FETCHING_ERROR = 'CITY_FETCHING_ERROR';
export const CITY_NAME_FETCHED = 'CITY_NAME_FETCHED';

export const SET_TIME_NOW = 'SET_TIME_NOW';

export const DAILY_FETCHING = 'DAILY_FETCHING';
export const DAILY_FETCHED = 'DAILY_FETCHED';
export const DAILY_FETCHING_ERROR = 'DAILY_FETCHING_ERROR';
export const SET_ID_DAILY = 'SET_ID_DAILY';
export const SET_SHOW_DAILY = 'SET_SHOW_DAILY';
export const SET_SHOW_DAILY_CONTENT = 'SET_SHOW_DAILY_CONTENT';

export const HOURLY_FETCHING = 'HOURLY_FETCHING';
export const HOURLY_FETCHED = 'HOURLY_FETCHED';
export const HOURLY_FETCHING_ERROR = 'HOURLY_FETCHING_ERROR';

export const SET_UPDATE_BTN = 'SET_UPDATE_BTN';